markdown: redcarpet
permalink: /:year/:month/:day/:title.html 
url: http://xjliao.me 
name: xjliao.me 
author: xjliao
qq: 909012329 
email: lxj990@gmail.com 
duoshuo: xjliao 
weibo: lxj990@gmail.com 
highlighter: pygments 
safe: true
tc: http://xjliao.qiniudn.com
paginate: 30
about: "你想作啥？"
github: http://github.com/xjliao/xjliao.github.io
