markdown: rdiscount 
permalink: /:title/
url: xjliao.me 
name: xjliao.me 
author: xjliao.me
qq: 909012329 
email: lxj990@gmail.com 
duoshuo: xjliao 
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo: lxj990@gmail.com 
github: xjliao.me 
pygments: true
safe: true
paginate: 30
about: "攻城狮一头，目前从事Linux的相关运维。	
热爱Linux，开源爱好者，喜欢虚拟化，github等。		
电脑洁癖与性能癖。  	
偶尔微博，偶尔wow。"
